const imgs={steak:'https://images.unsplash.com/photo-1741933793871-cf6217fecee3?auto=format&fit=crop&fm=jpg&q=82&w=900',dessert:'https://images.unsplash.com/photo-1625580832911-2bf3375bbefc?auto=format&fit=crop&fm=jpg&q=82&w=900',interior:'https://images.unsplash.com/photo-1776290347384-9e54dbb2ee29?auto=format&fit=crop&fm=jpg&q=82&w=900',sweet:'https://images.unsplash.com/photo-1675670515307-753fea18fc3d?auto=format&fit=crop&fm=jpg&q=82&w=900'};
const menu=[
['starter','Burrata & Heirloom Tomato','Creamy burrata, slow-roasted tomato, basil oil, aged balsamic.','PKR 1,450','Chef’s pick','interior'],['starter','Truffle Mushroom Velouté','Wild mushrooms, cream, truffle oil, sourdough crisp.','PKR 890','Vegetarian','interior'],['starter','Honey Sriracha Prawns','Seared prawns, honey chilli glaze, garlic aioli, herbs.','PKR 1,850','Popular','steak'],['starter','Beef Carpaccio','Pepper-crusted beef, capers, parmesan, lemon dressing.','PKR 1,650','Raw / cured','steak'],
['steak','28-Day Aged Ribeye','300g ribeye, charred shallot, pepper jus, triple-cooked fries.','PKR 4,950','Signature','steak'],['steak','Filet Mignon','250g tenderloin, potato purée, asparagus, red wine jus.','PKR 4,650','Guest favourite','steak'],['steak','Bone Marrow Striploin','300g striploin, marrow butter, roast garlic, seasonal greens.','PKR 4,350','Rich & smoky','steak'],['steak','Steak au Poivre','Tenderloin, cracked pepper crust, cognac cream, pommes frites.','PKR 4,750','Classic','steak'],
['sea','Pan-Seared Salmon','Norwegian salmon, lemon beurre blanc, potato fondant, greens.','PKR 3,950','Gluten friendly','steak'],['sea','Charred Red Snapper','Snapper fillet, herb couscous, caper butter, citrus salad.','PKR 2,650','Light','interior'],['sea','Garlic Butter Prawns','Tiger prawns, confit garlic, chilli butter, grilled sourdough.','PKR 2,450','Popular','steak'],
['pasta','Black Truffle Tagliolini','Fresh pasta, parmesan emulsion, black truffle, cracked pepper.','PKR 2,350','Vegetarian','interior'],['pasta','Prawn Linguine','Tiger prawns, cherry tomato, chilli, lemon, parsley.','PKR 2,150','House favourite','steak'],['pasta','Wild Mushroom Pappardelle','Mushroom ragù, mascarpone, parmesan, thyme.','PKR 1,850','Vegetarian','interior'],
['dessert','Veloura Chocolate','Dark chocolate crémeux, hazelnut praline, cocoa tuile.','PKR 1,150','Signature','dessert'],['dessert','Burnt Basque Cheesecake','Caramelized cheesecake, berry compote, vanilla cream.','PKR 950','Popular','sweet'],['dessert','Pistachio Tiramisu','Mascarpone, espresso sponge, pistachio cream, cocoa.','PKR 1,050','New','dessert'],['dessert','Seasonal Pavlova','Crisp meringue, vanilla chantilly, seasonal fruit.','PKR 900','Light','sweet']];
function draw(filter='all'){const g=document.querySelector('#menuGrid');g.innerHTML=menu.filter(x=>filter==='all'||x[0]===filter).map(x=>`<article class="dish"><div class="dish-img" style="background-image:url('${imgs[x[5]]}')"></div><div class="dish-body"><span class="tag">${x[4]}</span><div class="dish-top"><h3>${x[1]}</h3><span class="price">${x[3]}</span></div><p>${x[2]}</p></div></article>`).join('')};draw();
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelector('.filters .active').classList.remove('active');b.classList.add('active');draw(b.dataset.filter)});document.querySelector('.hamb').onclick=()=>document.querySelector('nav').classList.toggle('open');
const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('show')),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));window.addEventListener('load',()=>setTimeout(()=>document.querySelector('.loader').classList.add('hide'),500));
const form=document.querySelector('#bookingForm');form.onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));data.id='VL-'+Date.now().toString().slice(-6);data.created=new Date().toLocaleString();data.status='New';const arr=JSON.parse(localStorage.getItem('velouraBookings')||'[]');arr.unshift(data);localStorage.setItem('velouraBookings',JSON.stringify(arr));document.querySelector('#formMsg').innerHTML=`✓ Reservation received. Reference <b>${data.id}</b>. It is now visible in the included <a href="admin.html" style="color:#caa76b">Reservation Admin</a>.`;form.reset()};
